fn main() {
    let mut a_number = 16;
    let a_word = "CEVICHE";
    println!("The stored number is {}", a_number);
    a_number=23;
    println!("The new stored number is {}", a_number);
    println!("The stored word is {}", a_word);
    println!("*-------------*");
    let shadow = 8;
    let shadow = shadow - 2;
    let shadow = shadow * 2;
    println!("The shadow number is {}", shadow);
    println!("*---------------*");
    println!("Data types: numbers");
    println!("*---------------*");
    println!("Signed numbers");
    let s_number: i32 = -21;
    println!("The signed <<i32>> number is {}", s_number);
    println!("*---------------*");
    println!("Unsigned numbers");
    let number: u32 = 22;
    println!("The usigned <<u32>> number is {}", number);
    println!("*---------------*");
    println!("Floating-point numbers");
    let number_64f: f64 = 3.1;
    let number_32f: f32 = 4.6;
    println!("Floating point number <<64f>> is {}", number_64f);
    println!("Floating point number <<32f>> is {}", number_32f);
    println!("*-----------------*");
    println!("Some mathematical operations");
    let number_x: f64 = 7.0;
    let number_y: f64 = 23.0;
    println!("{} * {} = {}", number_x, number_y, number_x*number_y);
    println!("{} - {} = {}", number_x, number_y, number_x-number_y);
    println!("{} + {} = {}", number_x, number_y, number_x+number_y);
    println!("{} / {} = {}", number_x, number_y, number_x/number_y);
    println!("*----------------------------*");
    println!("Booleans: True or false");
    let is_bigger = 1 > 5;
    println!("Is {} > {}? {}", 1, 5, is_bigger);
    println!("*----------------------*");
    println!("Text: Characters and strings");
    let upper_st = 'S';
    let lower_st = 'g';
    let smile_face = '😃';
    println!("Uppercase letter: {}", upper_st);
    println!("Lowercase letter: {}", lower_st);
    println!("Smile face or emoticon: {}", smile_face);
    println!("*----------------------*");
    let character_1: char = 'S';
    let character_2: char = 'f';
    let smiley_face = '😃';
    let string_1 = "miley ";
    let string_2: &str = "ace";
    println!("{} is a {}{}{}{}", smiley_face, character_1, string_1, character_2, string_2);
}
